// IntelliJ Platform Gradle Plugin v2 (`org.jetbrains.intellij.platform`).
//
// Why v2 and not the legacy v1 `gradle-intellij-plugin`: v1 went into
// maintenance mode in 2024; v2 is the supported toolchain for IntelliJ
// 2024.2+, has first-class support for Marketplace publishing via
// `signPlugin`/`publishPlugin`, and uses the new IntelliJ Platform
// Repository (cuts download size dramatically vs. v1's bundled IDE).
//
// Build entry points:
//   * `./gradlew buildPlugin` — produces a .zip in build/distributions/
//     that can be installed via Marketplace OR `Settings → Plugins →
//     Install from disk`.
//   * `./gradlew runIde` — boots a sandbox IDE with the plugin loaded.
//     First run downloads the IDE distribution (~700 MB) and caches it
//     under `~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/`.
//   * `./gradlew verifyPlugin` — Marketplace pre-flight validation. CI
//     runs this on every PR; if it fails the plugin will be rejected at
//     upload time anyway.
//   * `./gradlew publishPlugin` — uploads to Marketplace; needs the
//     `JETBRAINS_MARKETPLACE_TOKEN` env var. The release workflow wires
//     this up automatically.

import org.jetbrains.intellij.platform.gradle.IntelliJPlatformType
import org.jetbrains.intellij.platform.gradle.TestFrameworkType

plugins {
    java
    kotlin("jvm") version "2.4.10"
    id("org.jetbrains.intellij.platform") version "2.16.0"
}

group = providers.gradleProperty("pluginGroup").get()
version = providers.gradleProperty("pluginVersion").get()

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        val type = providers.gradleProperty("platformType")
        val ver = providers.gradleProperty("platformVersion")
        create(type, ver)

        // No bundled-plugin dependencies needed for v0.1. If we later add
        // (e.g.) a TextMate-bundle-based highlighter, append:
        //   bundledPlugin("org.jetbrains.plugins.textmate")
        // and mirror it in plugin.xml `<depends>`.

        // instrumentationTools() dropped: removed in IntelliJ Platform
        // Gradle Plugin 2.12+ — the Java compiler dep is now auto-applied.
        pluginVerifier()
        zipSigner()
        testFramework(TestFrameworkType.Platform)
    }

    testImplementation("junit:junit:4.13.2")
    testImplementation("org.opentest4j:opentest4j:1.3.0")
}

tasks.wrapper {
    // CI generates the wrapper instead of checking in gradle-wrapper.jar;
    // the version comes from gradle.properties so no workflow repeats it.
    gradleVersion = providers.gradleProperty("gradleVersion").get()
}

// ---- generated engine coordinates -------------------------------------
// The plugin downloads the engine binary from the GitHub Release tagged
// `flatbuffers-format@<version>`. Both halves of that URL are generated
// rather than hand-copied into Kotlin: the version is read from the
// engine's own package.json (the single source release-please maintains),
// and the repository comes from gradle.properties. A hand-maintained copy
// would drift on any engine release and silently 404 for every user.
val generateEngineVersion = tasks.register("generateEngineVersion") {
    val enginePackageJson = layout.projectDirectory.file("../flatbuffers-formatter/package.json")
    val releaseRepo = providers.gradleProperty("pluginRepository")
    val outDir = layout.buildDirectory.dir("generated/engine-coordinates")
    inputs.file(enginePackageJson)
    inputs.property("releaseRepo", releaseRepo)
    outputs.dir(outDir)
    doLast {
        val pkg = enginePackageJson.asFile
        @Suppress("UNCHECKED_CAST")
        val parsed = groovy.json.JsonSlurper().parse(pkg) as Map<String, Any?>
        val version = parsed["version"] as? String
            ?: error("no top-level \"version\" in $pkg")
        val target = outDir.get().file("io/github/emindeniz99/intellij/EngineCoordinates.kt").asFile
        target.parentFile.mkdirs()
        target.writeText(
            """
            // GENERATED by the `generateEngineVersion` Gradle task — do not edit.
            // Sources: ../flatbuffers-formatter/package.json, gradle.properties.
            package io.github.emindeniz99.intellij

            internal const val GENERATED_ENGINE_VERSION: String = "$version"
            internal const val GENERATED_RELEASE_REPO: String = "${releaseRepo.get()}"

            """.trimIndent() + "\n",
        )
    }
}

kotlin {
    jvmToolchain(providers.gradleProperty("javaVersion").get().toInt())
    sourceSets["main"].kotlin.srcDir(generateEngineVersion)
}

intellijPlatform {
    pluginConfiguration {
        version = providers.gradleProperty("pluginVersion")

        // Plugin.xml's <description> and <change-notes> can also live
        // here as Gradle properties; we keep them inline in plugin.xml
        // so README + CHANGELOG stay the single source of truth and
        // diffs are reviewable without Gradle parsing.

        ideaVersion {
            // sinceBuild = 242.* means IntelliJ 2024.2.0 onward (and
            // every JetBrains IDE built on that platform: Rider 2024.2,
            // WebStorm 2024.2, etc.). untilBuild = null = no upper bound
            // — we'd rather get a "verify-plugin" warning when a future
            // IDE drops an API than artificially expire users.
            sinceBuild = "242"
            untilBuild = provider { null }
        }
    }

    pluginVerification {
        ides {
            // `recommended()` would auto-resolve to JetBrains'
            // current recommended-for-verification set, but that
            // list occasionally references IDE builds that aren't
            // yet downloadable from the public CDN (the indexer is
            // ahead of releases). Pinning explicit, known-shipped
            // builds is more reliable for CI.
            //
            // A three-point check across the supported range
            // (sinceBuild=242, no upper bound): the floor, the newest
            // IntelliJ, and the latest Rider. Few enough IDE downloads
            // to fit the runner disk and keep CI minutes down — the
            // floor is where breakage hides (an API newer than 242);
            // the newest is a forward sanity check.
            //
            // Type rule: IntelliJ IDEA Community (IC) only exists for
            // builds < 2025.3; 2025.3 unified IDEA into one product, so
            // the newest line uses the IntellijIdea (IU) type. Rider must
            // use the multi-OS ZIP — its installer isn't supported
            // (plugin issue #1852).
            create(IntelliJPlatformType.IntellijIdeaCommunity, "2024.2") // oldest, == sinceBuild 242
            create(IntelliJPlatformType.IntellijIdea, "2026.1")          // newest IntelliJ (post-merge unified type)
            create(IntelliJPlatformType.Rider, "2026.1") {               // latest Rider
                useInstaller = false
            }
        }
    }

    signing {
        // Marketplace signing keys come from CI env. Local builds skip
        // signing — the resulting unsigned .zip still installs via
        // "Install plugin from disk".
        certificateChainFile = providers.environmentVariable("JETBRAINS_CERTIFICATE_CHAIN")
            .map { file(it) }
            .orElse(provider { null })
        privateKeyFile = providers.environmentVariable("JETBRAINS_PRIVATE_KEY")
            .map { file(it) }
            .orElse(provider { null })
        password = providers.environmentVariable("JETBRAINS_PRIVATE_KEY_PASSWORD")
    }

    publishing {
        token = providers.environmentVariable("JETBRAINS_MARKETPLACE_TOKEN")
        // `channels = ["default"]` => public Marketplace listing.
        // Switch to ["beta"] to ship a prerelease without touching the
        // stable channel.
        channels = providers.gradleProperty("pluginVersion").map {
            listOf(if (it.contains("-")) "beta" else "default")
        }
    }
}

tasks {
    wrapper {
        gradleVersion = "9.5.1"
        distributionType = Wrapper.DistributionType.BIN
    }

    test {
        useJUnit()
    }
}
