const root = require("path").join(__dirname, "..", "..");

module.exports = require("node-gyp-build")(root);

try {
  module.exports.nodeTypeInfo = require("../../src/node-types.json");
} catch (_) {
  // node-types.json is generated by `tree-sitter generate`; if the
  // grammar wasn't regenerated yet we just omit the metadata.
}
